joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
steer_drive_controller:
  type        : "steer_drive_controller/SteerDriveController"
  rear_wheel: 'fake_drive_joint' # Rear wheel joint name
  front_steer: 'fake_steer_joint' # Front steer joint name
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0] 
# Frequency (in Hz) at which the odometry is published. Used for both tf and odom
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
# Diagonal of the covariance matrix for odometry twist publishing

# Wheel separation between the rear and the front, and diameter of the rear. 
# These are both optional.
# steer_drive_controller will attempt to read either one or both from the
# URDF if not specified as a parameter.
  wheel_separation_h : 0.5
  wheel_radius : 0.1

# Wheel separation and radius multipliers for odometry calibration.
  wheel_separation_h_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

# Steer position angle multipliers for fine tuning.
  steer_pos_multiplier       : 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 40

  # Base frame_id
  base_frame_id: base_link #default: base_link
  # Base frame_id, which is used to fill in the child_frame_id of the Odometry messages and TF.

  # Odom frame_id
  odom_frame_id: odom

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true # Whether the controller should limit linear speed or not.
      max_velocity           : 6.0  # m/s
      min_velocity           : -2.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 4.0  # m/s^2
      min_acceleration       : -2.5 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 3.0 # m/s^3

  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.5  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.5  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 1.5 # rad/s^3