gains:
  right_drive_wheel_joint  :  {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
  left_drive_wheel_joint   :  {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
  left_steer_joint   :  {p: 380.0, i: 50.5, d: 40.375}
  #left_steer_joint   :  {p: 100000.0, d: 10.0, i: 0.50, i_clamp: 3.0}
  right_steer_joint   :  {p: 380.0, i: 50.5, d: 14.375} 
  #right_steer_joint   :  {p: 100000.0, d: 10.0, i: 0.50, i_clamp: 3.0}
